version: '3.3'
services:
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    ports:
      - 1433:1433
    volumes:
      - dbdefault:/var/opt/mssql
    environment:
      - SA_PASSWORD=wkFl!16cQd
      - ACCEPT_EULA=Y
    container_name: db
  server:
    image: com.mera.inkrot.carshowroom/server:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - db
    ports:
      - 9000:9000
    environment:
      - spring.datasource.url=jdbc:sqlserver://db;databaseName=carshowroom
      - spring.datasource.username=SA
      - spring.datasource.password=wkFl!16cQd
    container_name: carshowroom
volumes:
  dbdefault:
    external: true