apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: carshowroom
  labels:
    app: carshowroom
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: carshowroom
    spec:
      containers:
        - name: carshowroom-app
          #image: gcr.io/carshowroom-241614/carshowroom:v0.1r
          image: CURRENT_BUILD_IMAGE_NAME
          env:
            - name: spring.datasource.url
              value: "jdbc:sqlserver://mssql;databaseName=carshowroom"
            - name: spring.datasource.username
              value: "SA"
            - name: spring.datasource.password
              valueFrom:
                secretKeyRef:
                  name: mssql-secrets
                  key: SA_PASSWORD
          imagePullPolicy: Always
          ports:
            - name: http-server
              containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  name: carshowroom
  labels:
    app: carshowroom
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http-server
  selector:
    app: carshowroom
