apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: carshowroom
  labels:
    app: carshowroom

spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: carshowroom
        #tier: frontend
    spec:
      containers:
        - name: carshowroom-app
          image: gcr.io/carshowroom-241614/carshowroom:v0.1
          imagePullPolicy: Always
          ports:
            - name: http-server
              containerPort: 8080
---
apiVersion: v1
kind: Service

metadata:
  name: carshowroom
  labels:
    app: carshowroom
    #tier: frontend

spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: http-server
  selector:
    app: carshowroom
    #tier: frontend